login/urls.py
from django.conf.urls import url, include
from login import views

#TEMPLATE TAGGING
app_name = 'login'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^user_login/$', views.user_login, name='user_login'),
]

reg_and_quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from django.urls import path

# Project Apps
from login import views as log
from lecturer import views as lecturer
from administrative import views as administrative
from student import views as student

from generic import utils

urlpatterns = [
	url(r'^$', log.index, name='login'),
	url(r'^$', lecturer.lect_home, name='Lect Home'),
	url(r'^$', administrative.admin_home, name='Admin Home'),
	path('admin/', admin.site.urls),
	url(r'^login/', include('login.urls')),
	url(r'^administrative/', include('administrative.urls')),
	url(r'^lecturer/', include('lecturer.urls')),
	url(r'^student/', include('student.urls')),
]

student/urls.py
from django.conf.urls import url
from student import views
from django.urls import path

app_name ='student'

urlpatterns = [
	path('', views.student_index, name='student_index'),
	path('my/', views.student_dashboard, name='student_dashboard'),
	path('code-input/', views.student_codeinput, name='student_codeinput'),
	path('submit-answer/', views.student_answer, name='student_answer'),
	path('error/', views.student_error, name='student_error'),
	path('user_logout', views.user_logout, name='user_logout'),
	path('attendance/<str:unit_t>/<str:period_id>/', views.student_stats, name='student_stats'),
]

student/models.py
from django.db import models
from administrative.models import Course
from lecturer.models import Published_Question, Class, Teaching_Day
from django.contrib.auth.models import User
from datetime import datetime, timedelta, timezone

class Student(models.Model):

    """
        Django's Model to represent the Student
		class in the MySQL Database.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student_profile', default='')
    s_class = models.ManyToManyField(Class, blank=True)                 # Many Students to Many Classes
    s_course= models.ManyToManyField(Course)                # Many Students to Many Courses

class Answer(models.Model):

	"""
		Django's Model to represent the Answer
		class in the MySQL.
	"""

	answers = (
		('answer_1', 'Answer 1'),
		('answer_2', 'Answer 2'),
		('answer_3', 'Answer 3'),
		('answer_4', 'Answer 4'),
	)
	
	s_id		= models.ForeignKey(Student, on_delete=models.PROTECT)		# Student ID
	q_id		= models.ForeignKey(Published_Question, on_delete=models.PROTECT)		# Question ID
	teach_day	= models.ForeignKey(Teaching_Day, on_delete=models.PROTECT)	# Teaching Day ID
	ans			= models.CharField(max_length=8, choices=answers)				# Answer Option
	tm_stmp		= models.DateTimeField(editable=False)					# Time Stamp
	ip_addr		= models.CharField(max_length=15)				# IP Type
	
	def save(self, *args, **kwargs):
		if not self.tm_stmp:
			self.tm_stmp = datetime.now(timezone.utc)
		return super(Answer, self).save(*args, **kwargs)
		
	def __str__(self):
		return self.s_id.user.username + ' ' + str(self.q_id.code) + ' ' + str(self.teach_day.date_td) + ' ' + self.ans + ' ' + str(self.tm_stmp) + self.q_id.question.topic_id.unit_id.code 

student/forms.py
from django import forms

class codeForm(forms.Form): 
    code = forms.IntegerField(label='Question Code')
    

student/views.py
# Author: Madyarini Grace Ariel
# Date: 23-03-2019
# Purpose: Render HTML pages for both static and dynamic types.
# Last Modified By: Madyarini Grace Ariel
# Last Modified Date: 23-03-2019

from django.urls import reverse
from django.shortcuts import render, redirect
from student.models import Student, Answer
from lecturer.models import Question, Published_Question, Teaching_Day, Class
from administrative.models import Unit, Teaching_Period
from datetime import datetime, timedelta, timezone
from student.forms import codeForm
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth import logout
from ipware import get_client_ip
from django.http import HttpResponse, HttpResponseRedirect
from lecturer.models import Class
from generic.decorator import is_student
from generic.utils import get_std_context, is_expired
from generic.graphs import attendance_graph
from django.contrib import messages

@login_required
@is_student
def student_index(request):
	"""
		Redirects to student's dashboard page.
		Parameters
		----------
		request: HTTP request object.
			Contains the request type sent by the user.
	"""
	return HttpResponseRedirect(reverse('student:student_dashboard'))

@login_required
@is_student
def student_dashboard(request):
	"""
		Renders student's dashboard page.
		Parameters
		----------
		request: HTTP request object.
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_std_context(user)

	return render(request, 'student/student_dashboard.html', user_dict)

@login_required
@is_student
def student_codeinput(request):
	"""
		Renders the form for question code input.
		Parameters
		----------
		request: HTTP request object.
			Contains the request type sent by the user.
	"""
	
	user = request.user
	user_dict = get_std_context(user)
	std = Student.objects.filter(user=user).first()
	
	if request.method == 'POST':
		form = codeForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			code = cd.get('code')
			item = Published_Question.objects.filter(code=code).first()
			if item is not None: # If Published_Question exists 
				if item.q_class in std.s_class.all():
					ans = Answer.objects.filter(s_id=std, q_id=item).first()
					if ans is None:
						if is_expired(item):
							messages.error(request, 'Question has expired', extra_tags='alert-warning')
							return redirect('student:student_codeinput')
						else:
							request.session['question_data'] = item.code
							return redirect('student:student_answer')
					else:
						messages.error(request, 'Duplicate answer is not allowed for a question.', extra_tags='alert-warning')  
						return redirect('student:student_codeinput')
				else:
					messages.error(request, 'Not your class question code.', extra_tags='alert-warning')  
					return redirect('student:student_codeinput')
			else:
				messages.error(request, 'No matching question code.', extra_tags='alert-warning')  
				return redirect('student:student_codeinput')
	else:
		form = codeForm()
		user_dict['form'] = form
		return render(request, 'student/studentInput.html', user_dict)

@login_required
@is_student
def student_answer(request):
	"""

		Renders the answer page for the student to submit answer.

		Parameters
		----------
		request: HTTP request object.
			Contains the request type sent by the user.
	"""

	if request.method == 'POST':
		if 'choice' in request.POST:

			# Get the student object who submitted the answer
			user = request.user
			std = Student.objects.filter(user=user).first()
			
			# Get the details of the question answered
			context = request.session.get('question_data')
			if context is not None:
				question_answered = Published_Question.objects.filter(code=context).first()
				if question_answered is not None:
					if is_expired(question_answered):
						messages.error(request, 'Question has expired', extra_tags='alert-warning')
						return redirect('student:student_codeinput')
					else:
						selection = request.POST.get('choice')

						class_item = question_answered.q_class

						enrolled_class = std.s_class.all()

						if class_item in enrolled_class:
							t_day = Teaching_Day.objects.filter(c_id=class_item, date_td=datetime.now(timezone.utc).date()).first()

							if t_day is None:
								messages.error(request, 'No matching Teaching Day found.', extra_tags='alert-warning')
								return redirect('student:student_codeinput')

							# Get IP address of student
							client_ip, is_routable = get_client_ip(request)

							if client_ip is None:
								client_ip = '0.0.0.0'

							# Create a new Answer object and save it to the database
							ans = Answer.objects.filter(s_id=std, q_id=question_answered)
							if ans.exists() == False :
								new_answer = Answer(s_id=std, q_id=question_answered, teach_day=t_day, ans=selection, ip_addr=client_ip)
								new_answer.save()

							request.session['question_data'] = None

							messages.success(request, 'Successfully submitted answer on Question: ' + question_answered.question.title, extra_tags='alert-success')
							return redirect('student:student_codeinput')
						else:
							messages.error(request, 'Not your class question.', extra_tags='alert-warning')
							return redirect('student:student_codeinput')
	else:
		context = request.session.get('question_data')
		if context is not None:
			user = request.user
			user_context = get_std_context(user)
			item = Published_Question.objects.filter(code=context).first()
			if item is not None:
				if is_expired(item):
					messages.error(request, 'Question has expired', extra_tags='alert-warning')
					return redirect('student:student_codeinput')
				else:
					context = {
						'unit_code' : item.question.topic_id.unit_id.code,
						'unit_title' : item.question.topic_id.unit_id.title,
						't_num' : item.question.topic_id.number,
						't_name' : item.question.topic_id.name,
						'q_title' : item.question.title,
						'ans1' : item.question.ans_1,
						'ans2' : item.question.ans_2,
					 	'ans3' : item.question.ans_3,
						'ans4' : item.question.ans_4,
					}
					user_dict = user_context.copy()
					user_dict.update(context)
					return render(request, 'student/studentQuestion.html', user_dict)
			else:
				return redirect('student:student_codeinput')
		else:
			messages.error(request, 'Input question code first.', extra_tags='alert-warning')  
			return redirect('student:student_codeinput')

@login_required
@is_student
def student_stats(request, unit_t, period_id):
	"""
		Handles request sent by the user when using the
		student statistics page. 

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	period = "".join(period_id.split()).upper().replace(',','-')
	unit = Unit.objects.filter(code=unit_t).first()
	student = Student.objects.filter(user=user).first()
	period = Teaching_Period.objects.filter(id=period).first()
	
	user_dict = get_std_context(user)
	user_dict['graph'] = attendance_graph(unit, period, student)
	user_dict['s_unit_code'] = unit.code
	user_dict['s_period'] = period_id

	return render(request, 'student/studentStats.html', user_dict)

@login_required
@is_student
def student_error(request):
	"""
		Renders error page. 

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_std_context(user)
	return render(request, 'student/error.html', user_dict)

@login_required
@is_student
def user_logout(request):
    """
        Closes the current session of the user,
        and redirects them to the login page.
        Parameters
        ----------
        request: HTTP request object
            Contains the request type sent by the user.
    """
    logout(request)
    return HttpResponseRedirect(reverse('login:user_login'))

templates/student/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
{% block head %}{% endblock head %}
<link rel="shortcut icon" href="https://moodleprod.murdoch.edu.au/pluginfile.php/1/theme_essential/favicon/1550717801/favicon%20%281%29.ico"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i,900,900i|Open+Sans:400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
<link rel="stylesheet" href="{% static "stylesheets/origin.css" %}">
<link rel="stylesheet" href="{% static "stylesheets/breadcrumb.css" %}">
</head>
<body>
<div class="content0">
<header role="banner">
    <nav id="essentialnavbar0" role="navigation" class="moodle-has-zindex nologo">
        <div class="navbar0">
            <div class="container-fluid0 navbar-inner0">
                <div class="row-fluid0">
                    <div class="custommenus0 pull-left0">
                        <a class="btn0 btn-navbar0" data-toggle="collapse0" data-target="#essentialmenus0">
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                        </a>
                        <a class="brand0" href="{% url 'student:student_dashboard' %}">LMS</a>
						<div class="pull-right0">
                        <div class="usermenu0 navbarrightitem0">
                            <ul class="nav0">
							<li class="dropdown0">
							<a class="dropdown-toggle0" data-toggle="dropdown0" href="{% url 'student:student_dashboard' %}">
							<img src="{% static 'images/loginicon.png' %}" alt="Picture of {{fl_name}}" title="Picture of {{fl_name}}" class="userpicture defaultuserpic" width="64" height="64" />
							<span class="profilename">{{f_name}}</span>
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<ul class="dropdown-menu0 pull-right0">
							<li><a href="{% url 'student:user_logout' %}"><em><span aria-hidden="true" class="fa0 fa-sign-out0"></span>Log out</em></a></li></ul></li></ul>
                                                </div>
                       <div class="messagemenu0 navbarrightitem0">
                            <div class="popover-region0 collapsed0 popover-region-messages0" id="nav-message-popover-container0" data-region="popover-region0">
</div>                   </div>
                        <div class="navbarrightitem0">
                                                    </div>
                        <div class="navbarrightitem0">
                                                    </div>
                    </div>
                        <div id="essentialmenus0" class="nav-collapse0 collapse0 pull-left0">
                            <div id="custom_menu_language" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"></ul></div>
							<div id="custom_menu_courses" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"><li class="dropdown0">
							<a href="{% url 'student:student_dashboard' %}" class="dropdown-toggle0" data-toggle="dropdown0" title="My units">
							<span aria-hidden="true" class="fa0 fa-briefcase0"></span>My units
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<div class="dropdown-menu0"><ul><li><a title="Dashboard" href="{% url 'student:student_dashboard' %}">
							<span><span aria-hidden="true" class="fa0 fa-home0"></span>
							<span> Dashboard</span></span></a></li>
							{% for unit, t_period in class_display %}
							<li><a title="{{unit.code}}{{t_period}}" href="{% url 'student:student_stats' unit_t=unit.code period_id=t_period %}"><span><span aria-hidden="true" class="fa fa-graduation-cap"></span>&nbsp;{{unit.code}} {{unit.title}} ({{t_period}})</span></a></li>
							{% endfor %}
							</ul></div></li></ul></div>
                    </div>
                </div>
            </div>
        </div>
		</div>
    </nav>
    <div id="page-header0" class="clearfix0 nologo0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <!-- HEADER: LOGO AREA -->
<div class="pull-left0"><a class="textlogo0" href="{% url 'student:student_dashboard' %}"><span id="headerlogo0" aria-hidden="true" class="fa0 fa-laptop0"></span><div class="titlearea0"><h1 id="title0">LMS</h1></div></a>                </div>
                            </div>
        </div>
    </div>
</header>
{% block main %}{% endblock main %}
</div>
<div id="space"></div>
 <footer role="contentinfo" id="page-footer0" class="footer0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <div class="tool_usertours-resettourcontainer span12"></div>
            </div>
        </div>
            <div class="footerlinks0 row-fluid0">
                <hr/>
                <span class="helplink0"></span>
                <span class="footer-login-info0"><div class="logininfo0">You are logged in as {{fl_name}} (<a href="{% url 'student:user_logout' %}">Log out</a>)</div></span>
                                <div class="footnote0 span12"><div id="footer0">
<div id="footer-content0">
<div class="container-fluid0">
 <div class="row-fluid0">
<div id="footer-logo0"><img alt="Murdoch University footer logo" src="{% static 'images/mu-port-white-284.png' %}" width="85" height="85"></div>
<div id="footer-legal0">
<ul>
<li>© 2019 Murdoch University</li>
<li>Copyright &amp; Disclaimer</li>
<li>TEQSA Number: PRV12163</li>
<li>CRICOS Code: 00125J</li>
</ul>
</div>
</div></div></div> </div></div></div>
</footer>
{% block script%}{% endblock script %}
</body>
</html>

templates/student/error.html
{% extends 'student/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ooops !!</title>
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{ % static 'stylesheets/error.css' %}">
{% endblock head %}
</head>
<body>
{% block main %}
    <main class="main">
        <section class=" d-flex align-items-center justify-content-center flex-column">
            <table class="table">
                <thead>
                    <th scope="col"><h1 class="text-center">Error</h1></th>
                </thead>
                <tbody>
                    <td scope="row" class="table__body"><h1  class="text-center">(Error Msg Here)</h1></td>
                </tbody>
            </table>
        </section>
    </main>
{% endblock main %}
{% block script %}
    <!--BootStrap Scripts-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>

templates/student/studentStats.html
{% extends 'student/base.html' %}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Attendance:</title>
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'stylesheets/lectQues.css' %}">
{% endblock head %}
</head>
<body>
{% block main %}
    <main class="main" style="margin-top:20px">
	<div id="page-top-header0" class="clearfix0">
<div id="page-navbar0" class="clearfix0 row-fluid0">
	<div class="breadcrumb-nav0 span9">
	<span class="accesshide0" id="navbar-label0">Page path</span>
	<nav aria-labelledby="navbar-label0"><ul class="breadcrumb0 style1"><li>
	<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a itemprop="url" href="{% url 'student:student_dashboard' %}"><span itemprop="title">Dashboard</span></a></span></li>
	<li><span tabindex="0">Check Attendance</span></li><li><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" title="{{s_unit_code}} {{s_period}}" aria-current="page" href="{% url 'student:student_stats' unit_t=s_unit_code period_id=s_period %}">
	<span itemprop="title">{{s_unit_code}} {{s_period}}</span></a></span></li>
	</ul></nav></div><nav class="breadcrumb-button0 span3"></nav>
</div>
</div>
<div id="page-content" style="margin-top:50px;">
            <section class=" d-flex align-items-center justify-content-center flex-column barchart">
            <h1 class="text-center">Attendance for {{s_unit_code}} ({{s_period}})</h1>
            <div>
            {{graph|safe}}
			</div>
             </section>
			 </div>
    </main>
{% endblock main %}
{% block script %}
    <!--BootStrap Scripts-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>

templates/student/student_dashboard.html
{% extends 'student/base.html' %}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
{% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Dashboard</title>
        <!--Font Awesome-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
                integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
                crossorigin="anonymous">

        <!--Bootstrap-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
                integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
                crossorigin="anonymous">

        <!--Student Css-->
        <link rel="stylesheet" href="{% static "stylesheets/Unitsview.css" %}">
{% endblock head %}
</head>
<body>
{% block main %}
<main class="main" style="margin-top:20px">
<div id="page-top-header0" class="clearfix0">
<div id="page-navbar0" class="clearfix0 row-fluid0">
	<div class="breadcrumb-nav0 span9">
	<span class="accesshide0" id="navbar-label0">Page path</span>
	<nav aria-labelledby="navbar-label0"><ul class="breadcrumb0 style1"><li>
	<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a itemprop="url" href="{% url 'student:student_dashboard' %}"><span itemprop="title">Dashboard</span></a></span></li>
	<!--
	<li><span tabindex="0">My online units</span></li><li><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb"><a itemprop="url" title="ICT302 IT Professional Practice Project (tja, 2019)" aria-current="page" href="https://moodleprod.murdoch.edu.au/course/view.php?id=12790">
	<span itemprop="title">ICT302tja_19</span></a></span></li>-->
	</ul></nav></div><nav class="breadcrumb-button0 span3"></nav>
</div>
</div>
                <h1 class="text-center main__heading">Dashboard</h1>
                <section class="container-fluid">
                        <section class="row">
                                 <section class="my-3 col-12 d-flex align-items-center justify-content-center flex-column unit">
                                                <form action="{% url 'student:student_codeinput' %}">
                                                        <section class="text-center form-group">
                                                                <input type="submit"
                                                                        class="btn btn-dark p-2 form__submit "
                                                                        value="Verify Question Code">
                                                        </section>
                                                </form>
                                        </h1>
                                </section>
								{% for unit, t_period in class_display %}
                                <section class="my-3 col-12 col-sm-6 d-flex align-items-center justify-content-center flex-column unit">
                                        <img class="unit__image"
                                                src="{% static 'images/'|add:unit.image %}">
                                        <h1 class="unit-text my-3 ">
                                                <span class="unit-text__main">{{unit.code}} {{unit.title}}</span>
                                                <span class="unit-text__sub">({{t_period}})</span>
                                                <form action="{% url 'student:student_stats' unit_t=unit.code period_id=t_period%}">
                                                        <section class="text-center form-group">
                                                                <input type="submit"
                                                                        class="btn btn-dark p-2 form__submit "
                                                                        value="Check Attendance">
                                                        </section>
                                                </form>
                                        </h1>
                                </section>
								{% endfor %}
                        </section>
                </section>
        </main>
{% endblock main %}
</body>
{% block script %}
<!--BootStrap Scripts-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% endblock script %}
</html>