administrative/urls.py
from django.conf.urls import url
from django.urls import path
from administrative import views
from generic import utils

# TEMPLATE TAGGING
app_name = 'administrative'

urlpatterns = [
	path('my/', views.admin_home, name='admin_home'),
	url(r'^account-management/$', views.acc_management, name='acc_management'),
	url(r'^unit-management/$', views.unit_management, name='unit_management'),
	url(r'^teaching-space-management/$', views.space_management, name='space_management'),
	url(r'^create-lecturer/$', views.employee_creation, name='employee_creation'),
	url(r'^create-student/$', views.student_creation, name='student_creation'),
	url(r'^stats/$', views.admin_stats, name='admin_stats'),
	url(r'^space_stats/$', views.space_stats, name='space_stats'),
	url(r'^attendance_stats/$', views.attendance_stats, name='attendance_stats'),
	path('error/', views.admin_error, name='admin_error'),
	url(r'^user-view/$', views.user_view, name='user_view'),
	url('user_login', views.user_logout, name='user_logout'),
]

login/urls.py
from django.conf.urls import url, include
from login import views

#TEMPLATE TAGGING
app_name = 'login'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^user_login/$', views.user_login, name='user_login'),
]

reg_and_quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from django.urls import path

# Project Apps
from login import views as log
from lecturer import views as lecturer
from administrative import views as administrative
from student import views as student

from generic import utils

urlpatterns = [
	url(r'^$', log.index, name='login'),
	url(r'^$', lecturer.lect_home, name='Lect Home'),
	url(r'^$', administrative.admin_home, name='Admin Home'),
	path('admin/', admin.site.urls),
	url(r'^login/', include('login.urls')),
	url(r'^administrative/', include('administrative.urls')),
	url(r'^lecturer/', include('lecturer.urls')),
	url(r'^student/', include('student.urls')),
]

student/urls.py
from django.conf.urls import url
from student import views
from django.urls import path

app_name ='student'

urlpatterns = [
	path('', views.student_index, name='student_index'),
	path('my/', views.student_dashboard, name='student_dashboard'),
	path('code-input/', views.student_codeinput, name='student_codeinput'),
	path('submit-answer/', views.student_answer, name='student_answer'),
	path('error/', views.student_error, name='student_error'),
	path('user_logout', views.user_logout, name='user_logout'),
	path('attendance/<str:unit_t>/<str:period_id>/', views.student_stats, name='student_stats'),
]

administrative/models.py
from django.db import models
from django.contrib.auth.models import User

class Building(models.Model):

	"""
		Django's Model to represent the building
		class in the MySQL database.
	"""

	code	= models.CharField(primary_key=True, max_length=4)	# Building's Code
	name	= models.CharField(max_length=255)			        # Building's Name

class Room(models.Model):

    """
                Django's Model to represent the room
                class in MySQL database.
    """

    id      = models.CharField(primary_key=True, max_length=255)     # Room's ID
    bd_code = models.ForeignKey(Building, on_delete=models.PROTECT) # Building Code
    level   = models.IntegerField()                                 # Room's level/Floor
    capacity= models.PositiveIntegerField()                         # Room's Capacity

class Course(models.Model):

	"""
		Django's Model to represent the course
		class in the MySQL Database.
	"""
	id	= models.CharField(primary_key=True, max_length=255)	# Course ID
	title	= models.CharField(max_length=255)				# Course's Title
	school	= models.CharField(max_length=255)				# School which owns the Course

class Unit(models.Model):

	"""
		Django's Model to represent the unit
		class in the MySQL database.
	"""

	code	= models.CharField(primary_key=True, max_length=255)		# Unit's code
	title 	= models.CharField(max_length=255)						# Unit Title
	credits = models.PositiveIntegerField()							# Unit's max credits
	image   = models.CharField(max_length=255, default='default.jpg')
	course_id = models.ManyToManyField(Course)

	def __str__(self):
		return self.code

class Employee(models.Model):

	"""
		Django's Model to represent the staff
		class in the MySQL database.
	"""

	user 	= models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile', default='')
	dpt		= models.CharField(max_length=255, blank=True, default='')		# Department
	pstn	= models.CharField(max_length=255, blank=True, default='')		# Position
	units	= models.ManyToManyField(Unit, blank=True)

class Teaching_Period(models.Model):

	"""
		Django's Model to represent the teaching period
		class in the MySQL database.
	"""

	id 	= models.CharField(primary_key=True, max_length=255)	# Teaching Period ID
	name	= models.CharField(max_length=255)				# Teaching Period Name
	st_date	= models.DateField()							# Starting Date
	en_date	= models.DateField()							# Ending Date
	
	def __str__(self):
		return self.id

administrative/views.py
# Author: Tomas Ramos
# Date: 20-03-2019
# Purpose: Render HTML pages for both static and dynamic types.
# Last Modified By: Tomas Ramos
# Last Modified Date: 23-03-2019

import csv
import io
import os
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from generic.utils import register_employee, register_student, find_user, register_room, register_building, find_room, find_building, register_units, register_courses, register_teaching_period, extract_info_student, extract_info_lecturer, edit_units
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.models import User
from student.models import Student
from administrative.models import Employee, Teaching_Period
from generic.utils import get_admin_context, admin_attendance_csv, admin_space_csv
from generic.decorator import is_admin
from generic.graphs import admin_room_usage, admin_attendance_graph
from django.contrib import messages
from generic.statistics_generator import stat_generator, csv_transfer, room_usage_csv

@login_required
def admin_home(request):
	"""
		Renders administratives' staff home page.

		Parameters
		----------
		request: HTTP request object.
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)
	return render(request, 'administrative/admin_home.html', user_dict)

@login_required
def acc_management(request):
	"""
		Renders the account management options page.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)
	return render(request, 'administrative/accountM.html', user_dict)

@login_required
def admin_stats(request):
	"""
		Handles request sent by the user when using the
		resource & attendance statistics page. 

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)
	return render(request, 'administrative/statistics.html', user_dict)

@login_required
def unit_management(request):
	"""
		Renders the unit management options page.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)

	if request.method == 'GET':
		return render(request, 'administrative/unitsM.html', user_dict)

	if request.method == "POST" and 'units_file' in request.FILES:
		csv_file = request.FILES['units_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_units(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:unit_management')
		else:
			messages.success(request, 'Units updated', extra_tags='alert-success')
			return redirect('administrative:unit_management')

	if request.method == "POST" and 'courses_file' in request.FILES:
		csv_file = request.FILES['courses_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_courses(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:unit_management')
		else:
			messages.success(request, 'Courses updated', extra_tags='alert-success')
			return redirect('administrative:unit_management')

	if request.method == "POST" and 'add_rm_file' in request.FILES:
		csv_file = request.FILES['add_rm_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = edit_units(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:unit_management')
		else:
			messages.success(request, 'Units of lecturers updated', extra_tags='alert-success')
			return redirect('administrative:unit_management')

	if request.method == "POST" and 'teaching_period_file' in request.FILES:
		csv_file = request.FILES['teaching_period_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_teaching_period(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:unit_management')
		else:
			messages.success(request, 'Teaching periods updated', extra_tags='alert-success')
			return redirect('administrative:unit_management')

	return render(request, 'administrative/unitsM.html', user_dict)

@login_required
def space_management(request):
	"""
		Renders the space management options page.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)

	# Re-render the page
	if request.method == "GET":
		return render(request, 'administrative/teachingspace.html', user_dict)

	# Process to obtain CSV - Rooms
	if request.method == "POST" and 'room_file' in request.FILES:
		csv_file = request.FILES['room_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_room(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:space_management')
		else:
			messages.success(request, "Rooms updated", extra_tags='alert-success')
			return redirect('administrative:space_management')

	# Process to obtain CSV - Buildings
	if request.method == "POST" and 'building_file' in request.FILES:
		csv_file = request.FILES['building_file']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_building(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:space_management')
		else:
			messages.success(request, "Buildings updated", extra_tags='alert-success')
			return redirect('administrative:space_management')

	# Process to find Rooms
	if request.method == "POST" and not request.POST.get('room_code') is None:
		room_code = request.POST.get('room_code')
		room = find_room(room_code)

	# Process to find Buildings
	if request.method == "POST" and not request.POST.get('building_code') is None:
		building_code = request.POST.get('building_code')
		building = find_building(building_code)

	return render(request, 'administrative/teachingspace.html', user_dict)

@login_required
def employee_creation(request):
	"""
		Handles request sent by the user when using the
		staff creation page. The page may be re-rendered or
		a file may be submitted.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)
	# Re-render the page
	if request.method == "GET":
		return render(request, 'administrative/lectAccAdd.html', user_dict)

	# Process to obtain CSV & create accounts
	if request.method == "POST" and 'files' in request.FILES:
		csv_file = request.FILES['files']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_employee(file_path)
		if status == False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:employee_creation')
		else:
			messages.success(request, 'Employee records updated', extra_tags='alert-success')
			return redirect('administrative:employee_creation')

	return render(request, 'administrative/lectAccAdd.html', user_dict)

@login_required
def student_creation(request):
	"""
		Handles request sent by the user when using the
		student creation page. The page may be re-rendered or
		a file may be submitted.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)

	# Process to render the page
	if request.method == "GET":
		return render(request, 'administrative/stuAccAdd.html', user_dict)

	# Process to obtain CSV & create accounts
	if request.method == "POST":
		csv_file = request.FILES['files']
		fs = FileSystemStorage()
		filename = fs.save(csv_file.name, csv_file)
		file_path = os.path.join(settings.MEDIA_ROOT, filename)
		status, msg = register_student(file_path)
		if status is False:
			messages.error(request, msg, extra_tags='alert-warning')
			return redirect('administrative:student_creation')
		else:
			messages.success(request, 'Student records updated', extra_tags='alert-success')
			return redirect('administrative:student_creation')

	return render(request, 'administrative/stuAccAdd.html', user_dict)

def attendance_stats(request):
	"""
		Handles request sent by the user when using the
		attendance statistics page.

		Parameters
		----------
		request: HTTP request object
			Contains the request type sent by the user.
	"""
	user = request.user
	user_dict = get_admin_context(user)
	user_dict['t_period'] = Teaching_Period.objects.all()
	if request.method == "POST":
		period = request.POST.get('period')
		granularity = request.POST.get('granularity')
		selection = request.POST.get('selection')

		if request.POST.get('submit'):
			graph = admin_attendance_graph(period, granularity, selection)
			if graph == False:
				messages.error(request, 'Information provided is wrong or the request object does not exists.', extra_tags='alert-warning')

templates/administrative/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
{% block head %}{% endblock head %}
<link rel="shortcut icon" href="https://moodleprod.murdoch.edu.au/pluginfile.php/1/theme_essential/favicon/1550717801/favicon%20%281%29.ico"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i,900,900i|Open+Sans:400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
<link rel="stylesheet" href="{% static "stylesheets/origin.css" %}">
<link rel="stylesheet" href="{% static "stylesheets/breadcrumb.css" %}">
</head>
<body>
<div class="content0">
<header role="banner">
    <nav id="essentialnavbar0" role="navigation" class="moodle-has-zindex nologo">
        <div class="navbar0">
            <div class="container-fluid0 navbar-inner0">
                <div class="row-fluid0">
                    <div class="custommenus0 pull-left0">
                        <a class="btn0 btn-navbar0" data-toggle="collapse0" data-target="#essentialmenus0">
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                        </a>
                        <a class="brand0" href="{% url 'administrative:admin_home' %}">LMS</a>
						<div class="pull-right0">
                        <div class="usermenu0 navbarrightitem0">
                            <ul class="nav0">
							<li class="dropdown0">
							<a class="dropdown-toggle0" data-toggle="dropdown0" href="{% url 'administrative:admin_home' %}">
							<img src="{% static 'images/loginicon.png' %}" alt="Picture of {{fl_name}}" title="Picture of {{fl_name}}" class="userpicture defaultuserpic" width="64" height="64" />
							<span class="profilename">{{f_name}}</span>
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<ul class="dropdown-menu0 pull-right0">
							<li><a href="{% url 'administrative:user_logout' %}"><em><span aria-hidden="true" class="fa0 fa-sign-out0"></span>Log out</em></a></li></ul></li></ul>
                                                </div>
                       <div class="messagemenu0 navbarrightitem0">
                            <div class="popover-region0 collapsed0 popover-region-messages0" id="nav-message-popover-container0" data-region="popover-region0">
</div>                   </div>
                        <div class="navbarrightitem0">
                                                    </div>
                        <div class="navbarrightitem0">
                                                    </div>
                    </div>
                        <div id="essentialmenus0" class="nav-collapse0 collapse0 pull-left0">
                            <div id="custom_menu_language" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"></ul></div>
							<div id="custom_menu_courses" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"><li class="dropdown0">
							<a href="{% url 'administrative:admin_home' %}" class="dropdown-toggle0" data-toggle="dropdown0" title="My units">
							<span aria-hidden="true" class="fa0 fa-briefcase0"></span>My features
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<div class="dropdown-menu0"><ul>
							<li><a title="Dashboard" href="{% url 'administrative:admin_home' %}"><span><span aria-hidden="true" class="fa0 fa-home0"></span><span> Dashboard</span></span></a></li>
							<li><a title="Teaching Space Management" href="{% url 'administrative:space_management' %}"><span><span aria-hidden="true" class="fa fa-chart-bar"></span>&nbsp;&nbsp;Teaching Space Management</span></a></li>
							<li><a title="Unit Management" href="{% url 'administrative:unit_management' %}"><span><span aria-hidden="true" class="fa fa-book-open"></span>&nbsp;&nbsp;Unit Management</span></a></li>
							<li><a title="Account Management" href="{% url 'administrative:acc_management' %}"><span><span aria-hidden="true" class="fa fa-user"></span>&nbsp;&nbsp;Account Management</span></a></li>
							<li><a title="Attendance Monitoring" href="{% url 'administrative:admin_stats' %}"><span><span aria-hidden="true" class="fa fa-check-circle"></span>&nbsp;&nbsp;Resource & Attendance Statistics</span></a></li>
							</ul></div></li></ul></div>
                    </div>
                </div>
            </div>
        </div>
		</div>
    </nav>
    <div id="page-header0" class="clearfix0 nologo0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <!-- HEADER: LOGO AREA -->
<div class="pull-left0"><a class="textlogo0" href="{% url 'administrative:admin_home' %}"><span id="headerlogo0" aria-hidden="true" class="fa0 fa-laptop0"></span><div class="titlearea0"><h1 id="title0">LMS</h1></div></a>                </div>
                            </div>
        </div>
    </div>
</header>
{% block main %}{% endblock main %}
</div>
<div id="space"></div>
 <footer role="contentinfo" id="page-footer0" class="footer0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <div class="tool_usertours-resettourcontainer span12"></div>
            </div>
        </div>
            <div class="footerlinks0 row-fluid0">
                <hr/>
                <span class="helplink0"></span>
                <span class="footer-login-info0"><div class="logininfo0">You are logged in as {{fl_name}} (<a href="{% url 'administrative:user_logout' %}">Log out</a>)</div></span>
                                <div class="footnote0 span12"><div id="footer0">
<div id="footer-content0">
<div class="container-fluid0">
 <div class="row-fluid0">
<div id="footer-logo0"><img alt="Murdoch University footer logo" src="{% static 'images/mu-port-white-284.png' %}" width="85" height="85"></div>
<div id="footer-legal0">
<ul>
<li>© 2019 Murdoch University</li>
<li>Copyright &amp; Disclaimer</li>
<li>TEQSA Number: PRV12163</li>
<li>CRICOS Code: 00125J</li>
</ul>
</div>
</div></div></div> </div></div></div>
</footer>
{% block script%}{% endblock script %}
</body>
</html>

templates/administrative/error.html
{% extends 'administrative/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{ % static 'stylesheets/error.css' %}">
{% endblock head %}
</head>
<body>
{% block main %}
    <main class="main">
        <section class=" d-flex align-items-center justify-content-center flex-column">
            <table class="table">
                <thead>
                    <th scope="col"><h1 class="text-center">Error</h1></th>
                </thead>
                <tbody>
                    <td scope="row" class="table__body"><h1  class="text-center">(Error Msg Here)</h1></td>
                </tbody>
            </table>
        </section>
    </main>
{% endblock main %}
{% block script %}
    <!--BootStrap Scripts-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>

templates/administrative/statistics.html
{% extends 'administrative/base.html' %}
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Administrator</title>
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather|Montserrat" rel="stylesheet">

    <!--Administrative-->
    <link rel="stylesheet" href="{% static "stylesheets/administrative.css" %}">
{% endblock head %}
</head>
<body>
{% block main %}
    <main class="main" style="margin-top:20px">
		<div id="page-top-header0" class="clearfix0">
<div id="page-navbar0" class="clearfix0 row-fluid0">
	<div class="breadcrumb-nav0 span9">
	<span class="accesshide0" id="navbar-label0">Page path</span>
	<nav aria-labelledby="navbar-label0"><ul class="breadcrumb0 style1"><li>
	<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a itemprop="url" href="{% url 'administrative:admin_home' %}"><span itemprop="title">Dashboard</span></a></span></li>
	<li><span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a itemprop="url" title="Update Class" aria-current="page" href="{% url 'administrative:admin_stats' %}">
	<span itemprop="title">Resource & Attendance Statistics</span></a></span></li>
	</ul></nav></div><nav class="breadcrumb-button0 span3"></nav>
</div>
</div>
		<div id="page-content">
        <section class="main__choices  d-flex align-items-center justify-content-center flex-column">
        <h1 class="mb-3 main__text">Features</h1>
        <a href="{% url 'administrative:attendance_stats' %}" class="btn btn-warning my-3 main__button"><i class="fas fa-chart-bar main__icon"></i>Attendance Statistics</a>
        <a href="{% url 'administrative:space_stats' %}" class="btn btn-warning my-3 main__button"><i class="fas fa-book-open main__icon"></i>Teaching Space Statistics</a>
        </section>
		</div>
    </main>
{% endblock main %}
{% block script %}
<!--BootStrap Scripts-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>