lecturer/urls.py
from lecturer import views
from django.conf.urls import url
from django.urls import path

#TEMPLATE TAGGING
app_name = 'lecturer'

urlpatterns = [
	path('', views.lect_home, name='lect_home'),
	path('units/<str:unit_code>/', views.lect_units, name='lect_units'),
	path('publish/<int:q_id>/<int:topic_id>/<str:period_id>/', views.lect_publish, name='lect_publish'),
	url('user_login', views.user_logout, name='user_logout'),
	url(r'^class/$', views.lect_class, name='lect_class'),
	path('qstats/<str:published_id>', views.lect_q_stats, name='lect_q_stats'),
	url(r'^project/$', views.lect_project, name='lect_project'),
	path('error/', views.lect_error, name='lect_error'),
	path('stats/<str:unit_t>/<str:period_id>', views.lect_stats, name='lect_stats'),
]

login/urls.py
from django.conf.urls import url, include
from login import views

#TEMPLATE TAGGING
app_name = 'login'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^user_login/$', views.user_login, name='user_login'),
]

reg_and_quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from django.urls import path

# Project Apps
from login import views as log
from lecturer import views as lecturer
from administrative import views as administrative
from student import views as student

from generic import utils

urlpatterns = [
	url(r'^$', log.index, name='login'),
	url(r'^$', lecturer.lect_home, name='Lect Home'),
	url(r'^$', administrative.admin_home, name='Admin Home'),
	path('admin/', admin.site.urls),
	url(r'^login/', include('login.urls')),
	url(r'^administrative/', include('administrative.urls')),
	url(r'^lecturer/', include('lecturer.urls')),
	url(r'^student/', include('student.urls')),
]

lecturer/models.py
# Author: Tomas Ramos
# Date: 20-03-2019
# Purpose: Render HTML pages for both static and dynamic types.
# Last Modified By: Madyarini
# Last Modified Date: 6-04-2019

from django.db import models
from administrative.models import Unit, Course, Teaching_Period, Room, Employee
from datetime import datetime, timezone

def today_utc():
	return datetime.utcnow().date()
	
class Topic(models.Model):
	"""
		Django's Model to represent the Topic
		class in the MySQL database.
	"""
	id = models.AutoField(primary_key=True)
	number = models.PositiveIntegerField()
	name = models.CharField(max_length=255)
	unit_id = models.ForeignKey(Unit, on_delete=models.PROTECT)

class Question(models.Model):
	"""
		Django's Model to represent the Question
		class in the MySQL database.
	"""
	answers = (
		('answer_1', 'Answer 1'),
		('answer_2', 'Answer 2'),
		('answer_3', 'Answer 3'),
		('answer_4', 'Answer 4'),
	)
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=255)
	text = models.CharField(max_length=255)
	ans_1 = models.CharField(max_length=255)
	ans_2 = models.CharField(max_length=255)
	ans_3 = models.CharField(max_length=255, blank=True, default='')
	ans_4 = models.CharField(max_length=255, blank=True, default='')
	topic_id = models.ForeignKey(Topic, on_delete=models.PROTECT)
	staff_id = models.ForeignKey(Employee, on_delete=models.PROTECT)
	correct_answer = models.CharField(max_length=8, choices=answers)

class Class(models.Model):
	"""
		Django's Model to represent the Class
		class in the MySQL database.
	"""
	FT = 'ft'
	PT = 'pt'
	INTERNAL_CHOICE =  'internal'
	EXTERNAL_CHOICE = 'external'
	time_commitments = (
		(FT, 'ft'),
		(PT, 'pt'),
		(INTERNAL_CHOICE, 'internal'),
		(EXTERNAL_CHOICE, 'external'),
	)
	id = models.AutoField(primary_key=True)
	unit_id	= models.ForeignKey(Unit, on_delete=models.PROTECT)
	t_period = models.ForeignKey(Teaching_Period, on_delete=models.PROTECT)
	staff_id = models.ForeignKey(Employee, on_delete=models.PROTECT, related_name='lecturer_id')
	time_commi = models.CharField(max_length=8, choices=time_commitments)
	code = models.CharField(max_length=1, blank=True, default='')

	def __str__(self):
		end_str = self.t_period.id + ' ' + '(' + self.time_commi + ')'
		if self.time_commi == 'ft' or self.time_commi == 'pt':
			return self.unit_id.code + self.code + ' ' + end_str
		else:
			return self.unit_id.code + ' ' + end_str
			
class Teaching_Day(models.Model):
	"""
		Django's Model to represent the Teaching Day
		class in the MySQL database.
	"""

	id      = models.AutoField(primary_key=True)
	r_id    = models.ForeignKey(Room, on_delete=models.PROTECT)     # Room ID
	c_id    = models.ForeignKey(Class, on_delete=models.PROTECT)    # Class ID
	date_td = models.DateField(default=today_utc)

class Published_Question(models.Model):
	"""
		Django's Model to represent the Published_Question
		class in the MySQL database.
	"""
	code = models.PositiveIntegerField(primary_key=True)               # Code - 123-456-789
	question = models.ForeignKey(Question, on_delete=models.PROTECT)   # Question object
	q_class = models.ForeignKey(Class, on_delete=models.PROTECT)
	tm_stmp = models.DateTimeField(editable=False)                  # Time automatically added
	minutes_limit = models.PositiveIntegerField()                      # Time in seconds to answer
	
	def save(self, *args, **kwargs):
		if not self.tm_stmp:
			self.tm_stmp = datetime.now(timezone.utc)
		return super(Published_Question, self).save(*args, **kwargs)

lecturer/forms.py
from django import forms
from django.forms import ModelForm
from . import models
from lecturer.models import Class
from administrative.models import Employee, Teaching_Period

class classForm(forms.ModelForm):
    class Meta:
        fields = ['unit_id', 't_period', 'time_commi', 'code']
        model = models.Class

    def __init__(self, user, *args, **kwargs):
        super(classForm, self).__init__(*args, **kwargs)
        emp = Employee.objects.filter(user=user).first()
        self.fields['unit_id'].queryset  = emp.units.all()

class pubQnForm(forms.ModelForm):
	class Meta:
		fields = ['q_class', 'minutes_limit']
		model = models.Published_Question
	
	def __init__(self, emp, unit, period, *args, **kwargs):
		super(pubQnForm, self).__init__(*args, **kwargs)
		self.fields['q_class'].widget.attrs['placeholder'] = 'Select Class'
		self.fields['q_class'].queryset  = Class.objects.filter(staff_id=emp, unit_id=unit, t_period=period)
		self.fields['minutes_limit'].widget.attrs['placeholder'] = 'Enter time limit in minutes'
		self.fields['q_class'].widget.attrs.update({'class':'form_custom'})
		self.fields['minutes_limit'].widget.attrs.update({'class':'form_custom'})

lecturer/views.py
import os
import re
from generic.utils import admin_attendance_csv
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from generic.utils import register_questions, publish_question, register_class, add_students, register_topics, get_lecturer_context, is_expired
from generic.graphs import answer_graph
from django.conf import settings
from administrative.models import Unit, Employee, Teaching_Period, Room
from lecturer.models import Class, Question, Topic, Teaching_Day, Published_Question
from lecturer.forms import classForm, pubQnForm
from datetime import datetime
from generic.decorator import is_lecturer
from generic.graphs import admin_attendance_graph
from django.contrib import messages
from datetime import datetime, timezone, timedelta

@login_required
@is_lecturer
def lect_home(request):
	user = request.user
	user_dict = get_lecturer_context(user)
	return render(request, 'Lecturer/lecturerHome.html', user_dict)

@login_required
@is_lecturer
def lect_publish(request, q_id, topic_id, period_id):

	user = request.user
	question = Question.objects.filter(id=q_id).first()
	topic = Topic.objects.filter(id=topic_id).first()
	period = Teaching_Period.objects.filter(id=period_id).first()

	user_dict = get_lecturer_context(user)
	user_dict['question_title'] = question.title
	
	emp = Employee.objects.filter(user=user).first()

	if request.method == "POST":
		form = pubQnForm(emp, topic.unit_id, period, request.POST)
		if form.is_valid():
			data = form.cleaned_data
			time = data.get('minutes_limit')
			curr_class = data.get('q_class')
			room = request.POST.get('current_room')
			
			room = Room.objects.filter(id=room).first()
			
			if room is not None:
				if Teaching_Day.objects.filter(c_id=curr_class).filter(date_td=datetime.utcnow().date()).first() is None:
					t_day = Teaching_Day(r_id=room, c_id=curr_class)
					t_day.save()

				code, question_item = publish_question(question, time, curr_class)
					
				request.session['question_data'] = question_item.code

				return redirect('lecturer:lect_project')
			else:
				messages.error(request, 'Invalid room code', extra_tags='alert-warning')
				return redirect('lecturer:lect_publish', q_id=q_id, topic_id=topic_id, period_id=period)
		else:
			messages.error(request, 'Invalid form input', extra_tags='alert-warning')
			return redirect('lecturer:lect_publish', q_id=q_id, topic_id=topic_id, period_id=period)
	else:
		form = pubQnForm(emp, topic.unit_id, period)
		user_dict['form'] = form

	return render(request, "Lecturer/LecturerPublish.html", user_dict)

@login_required
@is_lecturer
def lect_project(request):
	user = request.user
	user_context = get_lecturer_context(user)
	context = request.session.get('question_data')
	if context is not None:
		pub_qn = Published_Question.objects.filter(code=context).first()
		if pub_qn is not None:
			if is_expired(pub_qn):
				return redirect('lecturer:lect_error')
			else:
				code = str(pub_qn.code)
				code = code[:3] + ' - ' + code[3:6] + ' - ' + code[6:9]
				
				# Calculating remaining time 
				time_passed = datetime.now(timezone.utc) - pub_qn.tm_stmp
				seconds_passed = time_passed.total_seconds()
				seconds_remaining = pub_qn.minutes_limit * 60 - seconds_passed
				
				context2 = {
					'rem_time' : seconds_remaining,
					't_num' : pub_qn.question.topic_id.number,
					't_name' : pub_qn.question.topic_id.name,
					'text' : pub_qn.question.text,
					'code' : code,
				}
				user_dict = user_context.copy()
				user_dict.update(context2)
				return render(request, "Lecturer/lecturerProject.html", user_dict)
		else:
			return redirect('lecturer:lect_error')
	else:
		return redirect('lecturer:lect_error')

@login_required
@is_lecturer
def lect_units(request, unit_code):
	user = request.user
	empl = Employee.objects.filter(user=user).first()
	unit = Unit.objects.filter(code=unit_code).first()

	if unit is not None :
		if unit in empl.units.all():
			topic_list = Topic.objects.filter(unit_id=unit).order_by('number')

			question_list = []
			for x in topic_list:
				query = Question.objects.filter(topic_id=x)
				for y in query:
					question_list.append(y)

			t_period = Class.objects.filter(unit_id=unit, staff_id=empl).first().t_period

			user_dict = get_lecturer_context(user)
			user_dict['unit_code'] = unit.code
			user_dict['unit_title'] = unit.title
			user_dict['question_list'] = question_list
			user_dict['topic_list'] = topic_list
			user_dict['t_period'] = t_period

			if request.method == 'POST' and 'topic_file' in request.FILES:
				csv_file = request.FILES['topic_file']
				fs = FileSystemStorage()
				filename = fs.save(csv_file.name, csv_file)
				file_path = os.path.join(settings.MEDIA_ROOT, filename)
				status, msg = register_topics(file_path)
				if status == False:
					messages.error(request, msg, extra_tags='alert-warning')
					return redirect('lecturer:lect_units', unit_code=unit_code)
				else:
					messages.success(request, 'Topic records are updated.', extra_tags='alert-success')
					return redirect('lecturer:lect_units', unit_code=unit_code)
					
			if request.method == 'POST' and 'question_file' in request.FILES:
				csv_file = request.FILES['question_file']
				fs = FileSystemStorage()
				filename = fs.save(csv_file.name, csv_file)
				file_path = os.path.join(settings.MEDIA_ROOT, filename)
				status, msg = register_questions( file_path)
				if status == False:
					messages.error(request, msg, extra_tags='alert-warning')
					return redirect('lecturer:lect_units', unit_code=unit_code)
				else:
					messages.success(request, 'Question records are updated.', extra_tags='alert-success')
					return redirect('lecturer:lect_units', unit_code=unit_code)
					
			return render(request, "Lecturer/LecturerUnits.html", user_dict)
	
	return redirect('lecturer:lect_error')

@login_required
@is_lecturer
def lect_class(request):
	user = request.user
	user_dict = get_lecturer_context(user)

	if request.method == "POST":
		if 'student_file' in request.FILES:
			csv_file = request.FILES['student_file']
			fs = FileSystemStorage()
			filename = fs.save(csv_file.name, csv_file)
			file_path = os.path.join(settings.MEDIA_ROOT, filename)
			user = request.user
			status, msg = add_students(user, file_path)
			if status == False:
				messages.error(request, msg, extra_tags='alert-warning')
				return redirect('lecturer:lect_class')
			else:
				messages.success(request, 'Student records updated.', extra_tags='alert-success')
				return redirect('lecturer:lect_class')
		else:
			form = classForm(request.user, request.POST)
			if form.is_valid():
				data = form.cleaned_data
				unit = data.get('unit_id')
				period = data.get('t_period')
				time_commi2 = data.get('time_commi')
				code = data.get('code')
				cl = Class.objects.filter(unit_id=unit, t_period=period, time_commi=time_commi2, code=code)
				if cl.exists():
					messages.error(request, 'Class has existed', extra_tags='alert-warning')
					return redirect('lecturer:lect_class')
				else:
					emp = Employee.objects.filter(user=user).first()
					new_class = Class(unit_id=unit, t_period=period, staff_id=emp, time_commi=time_commi2, code=code)
					new_class.save()
					msg = 'Class ' + unit.code + code + ' was created successfully.'
					messages.success(request, msg, extra_tags='alert-success')
					return redirect('lecturer:lect_class')
			else:
				messages.error(request, 'Invalid form input', extra_tags='alert-warning')
				return redirect('lecturer:lect_class')
	else:
		form = classForm(request.user)
		user_dict['form'] = form
		return render(request, "Lecturer/lecturerClass.html", user_dict)

@login_required
@is_lecturer
def lect_q_stats(request, published_id):
	user = request.user
	code = int(re.sub('[^0-9]', '', published_id))
	
	pub_qn = Published_Question.objects.filter(code=code).first()
	
	if pub_qn is not None:
		time_passed = datetime.now(timezone.utc) - pub_qn.tm_stmp
		minutes_passed = int(time_passed.total_seconds() / 60)

		if minutes_passed < pub_qn.minutes_limit:
			pub_qn.minutes_limit = minutes_passed
			pub_qn.save()
		
		request.session['question_data'] = None
		
		user_dict = get_lecturer_context(user)
		
		context = {
			'graph' : answer_graph(code),
			'ans1' : pub_qn.question.ans_1,
			'ans2' : pub_qn.question.ans_2,
			'ans3' : pub_qn.question.ans_3,
			'ans4' : pub_qn.question.ans_4,
			'correct_ans' : pub_qn.question.correct_answer,
			'q_title' : pub_qn.question.title,
			'q_text' : pub_qn.question.text,
			't_num' : pub_qn.question.topic_id.number,
			't_name' : pub_qn.question.topic_id.name,
		}
		
		user_dict.update(context)
		
		return render(request, 'Lecturer/lecturerQuesStats.html', user_dict)
	else:
		return redirect('lecturer:lect_error')

@login_required
@is_lecturer
def lect_stats(request, unit_t, period_id):
	user = request.user
	user_dict = get_lecturer_context(user)

	unit = Unit.objects.filter(code=unit_t).first()
	if unit is not None:
		period = ''
		for letter in period_id.upper():
			if letter == ',':
				letter = '-'
			elif letter == ' ':
				continue
			period += letter
		period = Teaching_Period.objects.filter(id=period).first()
		if period is not None:
			emp = Employee.objects.filter(user=user).first()
			class_item = Class.objects.filter(unit_id=unit, t_period=period, staff_id=emp)

			if class_item.exists():
				user_dict['unit'] = unit_t
				user_dict['period'] = period_id
				if request.method == 'POST':
					code = request.POST.get('selection')
					if code[:6] == unit_t:
						if request.POST.get('submit'):
							graph = admin_attendance_graph(period, 'class', code)
							if graph == False:
								messages.error(request, 'Information provided is wrong or the request object does not exists.', extra_tags='alert-warning')

templates/Lecturer/base.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
{% block head %}{% endblock head %}
<link rel="shortcut icon" href="https://moodleprod.murdoch.edu.au/pluginfile.php/1/theme_essential/favicon/1550717801/favicon%20%281%29.ico"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i,900,900i|Open+Sans:400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
<link rel="stylesheet" href="{% static "stylesheets/origin.css" %}">
<link rel="stylesheet" href="{% static "stylesheets/breadcrumb.css" %}">
</head>
<body>
<div class="content0">
<header role="banner" style="margin-bottom:10px; padding-bottom:10px;">
    <nav id="essentialnavbar0" role="navigation" class="moodle-has-zindex nologo">
        <div class="navbar0">
            <div class="container-fluid0 navbar-inner0">
                <div class="row-fluid0">
                    <div class="custommenus0 pull-left0">
                        <a class="btn0 btn-navbar0" data-toggle="collapse0" data-target="#essentialmenus0">
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                            <span class="icon-bar0"></span>
                        </a>
                        <a class="brand0" href="{% url 'lecturer:lect_home' %}">LMS</a>
						<div class="pull-right0">
                        <div class="usermenu0 navbarrightitem0">
                            <ul class="nav0">
							<li class="dropdown0">
							<a class="dropdown-toggle0" data-toggle="dropdown0" href="{% url 'lecturer:lect_home' %}">
							<img src="{% static 'images/loginicon.png' %}" alt="Picture of {{fl_name}}" title="Picture of {{fl_name}}" class="userpicture defaultuserpic" width="64" height="64" />
							<span class="profilename">{{f_name}}</span>
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<ul class="dropdown-menu0 pull-right0">
                            <li><a href="{% url 'lecturer:lect_class' %}"><em><span aria-hidden="true" class="fa0 fa-create-class0"></span>Update Class</em></a></li>
							<li><a href="{% url 'lecturer:user_logout' %}"><em><span aria-hidden="true" class="fa0 fa-sign-out0"></span>Log out</em></a></li></ul></li></ul>
                                                </div>
                       <div class="messagemenu0 navbarrightitem0">
                            <div class="popover-region0 collapsed0 popover-region-messages0" id="nav-message-popover-container0" data-region="popover-region0">
</div>                   </div>
                        <div class="navbarrightitem0">
                                                    </div>
                        <div class="navbarrightitem0">
                                                    </div>
                    </div>
                        <div id="essentialmenus0" class="nav-collapse0 collapse0 pull-left0">
                            <div id="custom_menu_language" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"></ul></div>
							<div id="custom_menu_courses" class="custom_menu0 dropdownmenuscroll0"><ul class="nav0"><li class="dropdown0">
							<a href="{% url 'lecturer:lect_home' %}" class="dropdown-toggle0" data-toggle="dropdown0" title="My units">
							<span aria-hidden="true" class="fa0 fa-briefcase0"></span>My units
							<span aria-hidden="true" class="fa0 fa-caret-right0"></span></a>
							<div class="dropdown-menu0"><ul><li><a title="Dashboard" href="{% url 'lecturer:lect_home' %}">
							<span><span aria-hidden="true" class="fa0 fa-home0"></span>
							<span> Dashboard</span></span></a></li>
							<li><a title="Update Class" href="{% url 'lecturer:lect_class' %}"><span><span aria-hidden="true" class="fa0 fa-create-class0"></span>&nbsp;Update Class</span></a></li>
							{% for unit, t_period in class_display %}
							<li><a title="{{unit.code}}{{t_period}}" href="{% url 'lecturer:lect_units' unit_code=unit.code %}"><span><span aria-hidden="true" class="fa fa-graduation-cap"></span>&nbsp;{{unit.code}} {{unit.title}} ({{t_period}})</span></a></li>
							{% endfor %}
							</ul></div></li></ul></div>
                    </div>
                </div>
            </div>
        </div>
		</div>
    </nav>
    <div id="page-header0" class="clearfix0 nologo0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <!-- HEADER: LOGO AREA -->
<div class="pull-left0"><a class="textlogo0" href="{% url 'lecturer:lect_home' %}"><span id="headerlogo0" aria-hidden="true" class="fa0 fa-laptop0"></span><div class="titlearea0"><h1 id="title0">LMS</h1></div></a>                </div>
                            </div>
        </div>
    </div>
</header>
{% block main %}{% endblock main %}
</div>
<div id="space"></div>
 <footer role="contentinfo" id="page-footer0" class="footer0">
        <div class="container-fluid0">
            <div class="row-fluid0">
                <div class="tool_usertours-resettourcontainer span12"></div>
            </div>
        </div>
            <div class="footerlinks0 row-fluid0">
                <hr/>
                <span class="helplink0"></span>
                <span class="footer-login-info0"><div class="logininfo0">You are logged in as {{fl_name}} (<a href="{% url 'lecturer:user_logout' %}">Log out</a>)</div></span>
                                <div class="footnote0 span12"><div id="footer0">
<div id="footer-content0">
<div class="container-fluid0">
 <div class="row-fluid0">
<div id="footer-logo0"><img alt="Murdoch University footer logo" src="{% static 'images/mu-port-white-284.png' %}" width="85" height="85"></div>
<div id="footer-legal0">
<ul>
<li>© 2019 Murdoch University</li>
<li>Copyright &amp; Disclaimer</li>
<li>TEQSA Number: PRV12163</li>
<li>CRICOS Code: 00125J</li>
</ul>
</div>
</div></div></div> </div></div></div>
</footer>
{% block script%}{% endblock script %}
</body>
</html>

templates/Lecturer/lecturerHome.html
{% extends 'Lecturer/base.html' %}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
{% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Dashboard</title>
        <!--Font Awesome-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
                integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
                crossorigin="anonymous">

        <!--Bootstrap-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
                integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
                crossorigin="anonymous">

        <!--Student Css-->
        <link rel="stylesheet" href="{% static "stylesheets/Unitsview.css" %}">
{% endblock head %}
</head>
<body>
{% block main %}
<main class="main">
<div id="page-top-header0" class="clearfix0">
<div id="page-navbar0" class="clearfix0 row-fluid0">
	<div class="breadcrumb-nav0 span9">
	<span class="accesshide0" id="navbar-label0">Page path</span>
	<nav aria-labelledby="navbar-label0"><ul class="breadcrumb0 style1"><li>
	<span itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb">
	<a itemprop="url" href="{% url 'lecturer:lect_home' %}"><span itemprop="title">Dashboard</span></a></span></li>
	</ul></nav></div>
	<nav class="breadcrumb-button0 span3"></nav>
</div>
</div>
                <h1 class="text-center main__heading">Dashboard</h1>
                <section class="container-fluid">
                        <section class="row">
						{% for unit, t_period in class_display %}
                                <section
                                        class="my-3 col-12 col-sm-6 d-flex align-items-center justify-content-center flex-column unit">
                                        <img class="unit__image" src="{% static 'images/'|add:unit.image %}" alt="One of the unit images">
                                        <h1 class="unit-text my-3">
                                                <a href="{% url 'lecturer:lect_units' unit_code=unit.code %}"><span class="unit-text__main">{{unit.code}} {{unit.title}}</span>
                                                <span class="unit-text__sub">({{t_period}})</span></a>
                                        </h1>
										<form action="{% url 'lecturer:lect_stats' unit_t=unit.code period_id=t_period %}">
                                                        <section class="text-center form-group">
                                                                <input type="submit"
                                                                        class="btn btn-dark p-2 form__submit "
                                                                        value="Check Attendance">
                                                        </section>
                                </form>
                                </section>
								
						{% endfor %}
                        </section>
                </section>
        </main>
		{% endblock main %}
<!--BootStrap Scripts-->
{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% endblock script %}
</body>
</html>